# Generated by Django 5.0.6 on 2024-07-13 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(blank=True, max_length=100, null=True)),
                ('range', models.CharField(blank=True, max_length=100, null=True)),
                ('from_year', models.IntegerField(blank=True, null=True)),
                ('to_year', models.IntegerField(blank=True, null=True)),
                ('spec_notes', models.TextField(blank=True, null=True)),
                ('telemute', models.BooleanField(default=False)),
                ('kram', models.BooleanField(default=False)),
                ('mounting_notes', models.TextField(blank=True, null=True)),
                ('mute_pin', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('pkg0', models.CharField(blank=True, max_length=255, null=True)),
                ('pkg1', models.CharField(blank=True, max_length=255, null=True)),
                ('pkg2', models.CharField(blank=True, max_length=255, null=True)),
                ('pkg3', models.CharField(blank=True, max_length=255, null=True)),
                ('pkg4', models.CharField(blank=True, max_length=255, null=True)),
                ('pkg5', models.CharField(blank=True, max_length=255, null=True)),
                ('pkg6', models.CharField(blank=True, max_length=255, null=True)),
                ('pkg7', models.CharField(blank=True, max_length=255, null=True)),
                ('pkg8', models.CharField(blank=True, max_length=255, null=True)),
                ('pkg9', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
    ]
