# Generated by Django 5.0.6 on 2025-03-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsku',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='product_skus', to='products.supplier'),
        ),
    ]
