# Generated by Django 5.0.6 on 2024-07-16 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('stock', '0002_alter_po_invoice_number_alter_po_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.stockcontrolcode'),
        ),
    ]
