# Generated by Django 5.0.6 on 2024-08-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_code',
        ),
    ]
