# Generated by Django 5.0.6 on 2024-09-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cardata_created_at_cardata_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardata',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardata',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='package',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='po',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='po',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productsku',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productsku',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stockcontrolcode',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockcontrolcode',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stocksuppliedto',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocksuppliedto',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
    ]
