# Generated by Django 5.0.6 on 2025-03-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('products', '0002_subscriptionplan_companysubscription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysubscription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='companysubscription',
            unique_together={('company', 'plan')},
        ),
        migrations.AddIndex(
            model_name='companysubscription',
            index=models.Index(fields=['company'], name='Company Sub_company_514336_idx'),
        ),
        migrations.AddIndex(
            model_name='companysubscription',
            index=models.Index(fields=['plan'], name='Company Sub_plan_id_cc2e51_idx'),
        ),
        migrations.AddIndex(
            model_name='companysubscription',
            index=models.Index(fields=['status'], name='Company Sub_status_e1da04_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['tier'], name='Subscriptio_tier_2ff757_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['billing_cycle'], name='Subscriptio_billing_786a82_idx'),
        ),
        migrations.AlterModelTable(
            name='companysubscription',
            table='Company Subscriptions',
        ),
        migrations.AlterModelTable(
            name='subscriptionplan',
            table='Subscription Plans',
        ),
    ]
