# Generated by Django 5.0.6 on 2024-08-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasteerror',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
