# Generated by Django 5.0.6 on 2024-09-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cardata_is_deleted_cardata_is_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardata',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='po',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='productsku',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='stockcontrolcode',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='stocksuppliedto',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='is_updated',
            new_name='is_active',
        ),
    ]
