# Generated by Django 5.0.6 on 2024-08-17 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_pasteerror_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasteerror',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
