# Generated by Django 5.0.6 on 2024-08-22 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_pasteerror_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pkg0',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pkg1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pkg2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pkg3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pkg4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pkg5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pkg6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pkg7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pkg8',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pkg9',
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='products.product')),
            ],
        ),
    ]
