# Generated by Django 5.0.6 on 2024-10-12 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsku',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_skus', to='products.product'),
        ),
    ]
