# Generated by Django 5.0.6 on 2024-08-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productsku_delete_pasteerror'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsku',
            options={'verbose_name': 'ProductSKUs'},
        ),
    ]
