# Generated by Django 5.0.6 on 2024-12-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_po_product_po_product_sku_stockmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='operation_type',
            field=models.CharField(choices=[('remove', 'Remove'), ('add', 'Add'), ('adjust', 'Adjust')], max_length=10),
        ),
    ]
