# Generated by Django 5.0.6 on 2024-12-30 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_po_invoice_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_price',
        ),
    ]
