# Generated by Django 5.0.6 on 2024-08-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productsku_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsku',
            options={'verbose_name_plural': 'ProductSKUs'},
        ),
    ]
