# Generated by Django 5.0.6 on 2024-08-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productsku_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardata',
            options={'verbose_name_plural': 'CarData'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='po',
            options={'verbose_name_plural': 'POs'},
        ),
    ]
