# Generated by Django 5.0.6 on 2024-08-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_cardata_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocksuppliedto',
            options={'verbose_name_plural': 'StockSuppliedTos'},
        ),
    ]
