# Generated by Django 5.0.6 on 2024-08-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_stocksuppliedto_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsku',
            name='sku_code',
        ),
    ]
