# Generated by Django 5.0.6 on 2024-08-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_productsku_sku_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
