# Generated by Django 5.0.6 on 2025-03-08 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('refund_reason', models.TextField(blank=True, null=True)),
                ('refund_initiated', models.DateTimeField(blank=True, null=True)),
                ('refund_completed', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('admin_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Refund',
                'verbose_name_plural': 'Order Refunds',
                'db_table': 'order_refunds',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('return_status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='requested', max_length=20)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pickup_address', models.JSONField(blank=True, default=dict, null=True)),
                ('drop_off_address', models.JSONField(blank=True, default=dict, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('shipment_mode', models.CharField(choices=[('pickup', 'Customer Pickup'), ('dropoff', 'Dropoff at Center'), ('courier', 'Courier Service')], default='dropoff', max_length=32)),
                ('cancellation_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('return_rejected_reason', models.TextField(blank=True, null=True)),
                ('return_rejected_by', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_restocked', models.BooleanField(default=False)),
                ('restocked_at', models.DateTimeField(blank=True, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
                ('order_refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='return_items', to='orders.orderrefund')),
            ],
            options={
                'db_table': 'return_items',
            },
        ),
    ]
