# Generated by Django 5.0.6 on 2024-08-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_product'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='order_products', to='products.product'),
        ),
    ]
