# Generated by Django 5.0.6 on 2025-05-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_customerinvoice_engineerinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoice',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
