# Generated by Django 5.0.6 on 2024-09-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_deleted_order_is_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='is_updated',
            new_name='is_active',
        ),
    ]
