# Generated by Django 5.0.6 on 2024-10-20 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rename_is_updated_credit_is_active_and_more'),
        ('engineers', '0006_alter_engineer_contact_name'),
        ('orders', '0005_booking_created_at_booking_created_by_and_more'),
        ('products', '0006_alter_productsku_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_engineers', to='engineers.engineer'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_credits', to='customers.credit'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_orders', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_skus', to='products.productsku'),
        ),
    ]
