# Generated by Django 5.0.6 on 2024-08-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options_alter_customercompany_options_and_more'),
        ('orders', '0006_rename_products_order_product'),
        ('products', '0012_remove_productsku_sku_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KIF',
            new_name='OrderItem',
        ),
    ]
