# Generated by Django 5.0.6 on 2024-08-22 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orderitem_options_remove_orderitem_qty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='product_sku',
        ),
    ]
