# Generated by Django 5.0.6 on 2024-12-07 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_engineer_notes_order_purchasing_notes'),
        ('products', '0007_remove_po_product_po_product_sku_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.po'),
        ),
    ]
