# Generated by Django 5.0.6 on 2024-08-28 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_product_orderitem_product_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_sku',
            new_name='product',
        ),
    ]
