# Generated by Django 5.0.6 on 2025-01-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
        migrations.DeleteModel(
            name='CustomerCompany',
        ),
    ]
