# Generated by Django 5.0.6 on 2024-07-16 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='customers_i_custome_e86ce7_idx',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='dispute_eng_inv',
            new_name='is_dispute_eng_inv',
        ),
        migrations.AlterField(
            model_name='customer',
            name='dispute_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='late',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ManyToManyField(related_name='customer_invoices', to='customers.customer'),
        ),
    ]
