# Generated by Django 5.0.6 on 2025-04-13 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0002_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('feedback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='customers.customer')),
                ('order_referance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='products.productsku')),
            ],
            options={
                'db_table': 'customer_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer'], name='customer_fe_custome_d9ac95_idx'), models.Index(fields=['product'], name='customer_fe_product_1f9e58_idx'), models.Index(fields=['rating'], name='customer_fe_rating_575b42_idx'), models.Index(fields=['status'], name='customer_fe_status_827c34_idx'), models.Index(fields=['order_referance'], name='customer_fe_order_r_0a8f76_idx'), models.Index(fields=['-created_at'], name='customer_fe_created_c9ecda_idx')],
            },
        ),
    ]
