# Generated by Django 5.0.6 on 2024-08-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customercompany',
            options={'verbose_name_plural': 'customer_companies'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_ref_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
