# Generated by Django 5.0.6 on 2024-08-23 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options_alter_customercompany_options_and_more'),
        ('utilities', '0002_vehiclemake_remove_vehiclemodel_model_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='vehicle_make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.vehiclemake'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.vehiclemodel'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.vehicletype'),
        ),
    ]
