# Generated by Django 5.0.6 on 2024-09-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_credit_created_by_credit_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credit',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customercompany',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customercompany',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoiceservicelog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoiceservicelog',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
    ]
