# Generated by Django 5.0.6 on 2025-05-04 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('customers', '0002_initial'),
        ('products', '0001_initial'),
        ('utilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfeedback',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='products.productsku'),
        ),
        migrations.AddField(
            model_name='customerinstallation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customerkit',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customermiscellaneous',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miscellaneous', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customermiscellaneous',
            name='customer_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customermiscellaneous',
            name='dispute_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customermiscellaneous',
            name='sold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customernotification',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='vehicle_make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='make', to='utilities.vehiclemake'),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model', to='utilities.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type', to='utilities.vehicletype'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ManyToManyField(related_name='customer_invoices', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='credit',
            name='original_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceservicelog',
            name='account_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices', to='customers.invoice'),
        ),
        migrations.AddIndex(
            model_name='customerfeedback',
            index=models.Index(fields=['customer'], name='customer_fe_custome_d9ac95_idx'),
        ),
        migrations.AddIndex(
            model_name='customerfeedback',
            index=models.Index(fields=['product'], name='customer_fe_product_1f9e58_idx'),
        ),
        migrations.AddIndex(
            model_name='customerfeedback',
            index=models.Index(fields=['rating'], name='customer_fe_rating_575b42_idx'),
        ),
        migrations.AddIndex(
            model_name='customerfeedback',
            index=models.Index(fields=['status'], name='customer_fe_status_827c34_idx'),
        ),
        migrations.AddIndex(
            model_name='customerfeedback',
            index=models.Index(fields=['order_referance'], name='customer_fe_order_r_0a8f76_idx'),
        ),
        migrations.AddIndex(
            model_name='customerfeedback',
            index=models.Index(fields=['-created_at'], name='customer_fe_created_c9ecda_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='customers_i_invoice_28657c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['created_at'], name='customers_i_created_4d45d9_idx'),
        ),
    ]
