# Generated by Django 5.0.6 on 2024-09-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_credit_is_deleted_credit_is_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='customercompany',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='invoiceservicelog',
            old_name='is_updated',
            new_name='is_active',
        ),
    ]
