# Generated by Django 5.0.6 on 2024-08-26 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_vehicle_make_and_more'),
        ('utilities', '0002_vehiclemake_remove_vehiclemodel_model_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='acc_inv_paid',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='acc_inv_raised_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='back_order',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='booking_notes',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='call_back_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='call_back_reason',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='complaint_detail',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='complaint_resolution',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='consignment',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='courier_tracking_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='courtesy_call',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='courtesy_notes',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_confirmed_by',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_confirmed_time',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_notified',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_notified_time',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date_of_install',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='delivery_address_2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='delivery_address_3',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='delivery_address_4',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='delivery_notes',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='delivery_postcode',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='dispute_by',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='dispute_eng_reason',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email_request_confirmed',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='eng_inv_no',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='engineer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='existing_kit',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='install_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='install_address_2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='install_address_3',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='install_address_4',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='install_notes',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='instlev',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='invoice_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='invoice_note',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='invoice_paid',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='invoice_received',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_dispatch_printed',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_dispute_eng_inv',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_hot',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_on_hold',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_purchasing_complete',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='jcd',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='job_required',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='kit_confirm_delivery',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='kit_delivered_to',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='kit_delivery_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='kit_installed',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='kit_order_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='kit_supplied',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='late',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='original_complaint_date_time',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='package',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='po_number_kit',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='post_code1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='postcode2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='preferred_install_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='purchasing_complete_time',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='record_edited_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='request_time_stamp',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='resolution_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sat',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='service_call_enabled',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='service_call_reference',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='service_call_rod',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='service_reference',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='service_reference_org',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sold_by',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='stock_to_be_returned',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='time_of_install',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='vehicle_make',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='who_took_complaint',
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_3', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_4', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(max_length=20)),
                ('address_type', models.CharField(choices=[('INSTALL', 'Install'), ('DELIVERY', 'Delivery'), ('INVOICE', 'Invoice')], max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_call_rod', models.CharField(blank=True, max_length=100, null=True)),
                ('service_call_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('original_complaint_date_time', models.DateTimeField(blank=True, null=True)),
                ('complaint_detail', models.TextField(blank=True, null=True)),
                ('complaint_resolution', models.TextField(blank=True, null=True)),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='customers.customer')),
                ('who_took_complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_taken', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_installed', models.CharField(blank=True, max_length=100, null=True)),
                ('job_required', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_notes', models.TextField(blank=True, null=True)),
                ('date_of_install', models.DateField(blank=True, null=True)),
                ('time_of_install', models.TimeField(blank=True, null=True)),
                ('install_notes', models.TextField(blank=True, null=True)),
                ('preferred_install_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_supplied', models.BooleanField(default=False)),
                ('po_number_kit', models.CharField(blank=True, max_length=100, null=True)),
                ('kit_order_date', models.DateField(blank=True, null=True)),
                ('kit_delivered_to', models.CharField(blank=True, max_length=255, null=True)),
                ('kit_delivery_date', models.DateField(blank=True, null=True)),
                ('kit_confirm_delivery', models.DateField(blank=True, null=True)),
                ('delivery_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('courier_tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_received', models.DateTimeField(blank=True, null=True)),
                ('invoice_paid', models.DateTimeField(blank=True, null=True)),
                ('invoice_note', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMiscellaneous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('is_purchasing_complete', models.BooleanField(default=False)),
                ('purchasing_complete_time', models.DateTimeField(blank=True, null=True)),
                ('customer_confirmed_time', models.DateTimeField(blank=True, null=True)),
                ('acc_inv_raised_date', models.DateField(blank=True, null=True)),
                ('acc_inv_paid', models.CharField(blank=True, max_length=255, null=True)),
                ('is_on_hold', models.BooleanField(default=False)),
                ('record_edited_at', models.DateTimeField(blank=True, null=True)),
                ('service_reference_org', models.CharField(blank=True, max_length=100, null=True)),
                ('call_back_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_to_be_returned', models.CharField(blank=True, max_length=100, null=True)),
                ('service_call_enabled', models.BooleanField(default=False)),
                ('call_back_date', models.DateField(blank=True, null=True)),
                ('instlev', models.CharField(blank=True, max_length=100, null=True)),
                ('is_dispatch_printed', models.BooleanField(default=False)),
                ('eng_inv_no', models.CharField(blank=True, max_length=100, null=True)),
                ('is_hot', models.BooleanField(default=False)),
                ('jcd', models.DateField(blank=True, null=True)),
                ('sat', models.BooleanField(default=False)),
                ('late', models.IntegerField(blank=True, null=True)),
                ('consignment', models.CharField(blank=True, max_length=100, null=True)),
                ('is_dispute_eng_inv', models.BooleanField(default=False)),
                ('dispute_eng_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('back_order', models.BooleanField(default=False)),
                ('existing_kit', models.BooleanField(default=False)),
                ('package', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miscellaneous', to='customers.customer')),
                ('customer_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_customers', to=settings.AUTH_USER_MODEL)),
                ('dispute_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_notified', models.BooleanField(default=False)),
                ('customer_notified_time', models.DateTimeField(blank=True, null=True)),
                ('email_request_confirmed', models.BooleanField(default=False)),
                ('request_time_stamp', models.DateTimeField(blank=True, null=True)),
                ('courtesy_call', models.BooleanField(default=False)),
                ('courtesy_notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='customers.customer')),
                ('vehicle_make', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.vehiclemake')),
                ('vehicle_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.vehiclemodel')),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.vehicletype')),
            ],
        ),
    ]
