# Generated by Django 5.0.6 on 2025-05-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_initial'),
        ('orders', '0002_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customerfeedback',
            name='customer_fe_order_r_0a8f76_idx',
        ),
        migrations.RenameField(
            model_name='customerfeedback',
            old_name='order_referance',
            new_name='order',
        ),
        migrations.AddIndex(
            model_name='customerfeedback',
            index=models.Index(fields=['order'], name='customer_fe_order_i_4811ca_idx'),
        ),
    ]
