# Generated by Django 5.0.6 on 2024-08-26 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_customer_acc_inv_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='customermiscellaneous',
            name='existing_kit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
