# Generated by Django 5.0.6 on 2024-08-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customeraddress_customer_and_more'),
        ('utilities', '0003_remove_vehiclemodel_vehicle_make'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerVehicle',
            new_name='CustomerVehicleInfo',
        ),
    ]
