# Generated by Django 5.0.6 on 2025-01-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_engineer_company',
            field=models.BooleanField(default=False),
        ),
    ]
