# Generated by Django 5.0.6 on 2024-07-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verfication_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
