# Generated by Django 5.0.6 on 2024-09-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_is_deleted_account_is_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='audittrail',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='bulletin',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='installlevel',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='notifiedby',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='userrole',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_updated',
        ),
    ]
