# Generated by Django 5.0.6 on 2024-10-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_is_updated_account_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='install_level',
        ),
        migrations.RemoveField(
            model_name='account',
            name='opened',
        ),
        migrations.RemoveField(
            model_name='account',
            name='opened_by',
        ),
    ]
