services:
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  web_app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: vision_telematics
    hostname: vision_telematics
    command: >
      sh -c "
      python manage.py collectstatic --no-input &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/webapp
    env_file:
      - ./.env
    environment:
      GUNICORN_PORT: 8000
      CELERY_BROKER_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_started

  celery:
    build:
      context: .
    container_name: celery_worker
    command: celery -A config.celery worker -l info
    volumes:
      - .:/webapp
    depends_on:
      - web_app
      - redis
    env_file:
      - .env

volumes:
  pg_data:
