# Generated by Django 5.0.6 on 2025-04-07 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('customers', '0001_initial'),
        ('engineers', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('invoice_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('action_title', models.CharField(blank=True, max_length=255, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('service_call', models.CharField(blank=True, max_length=100, null=True)),
                ('service_call_date', models.DateField(blank=True, null=True)),
                ('action_required', models.CharField(blank=True, max_length=255, null=True)),
                ('call_back_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('actioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_occured_by', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_resolved_by', to=settings.AUTH_USER_MODEL)),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_taken_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_care',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('service_ref', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('first_return_visit', models.DateField(blank=True, null=True)),
                ('fault_reported_date', models.DateField(blank=True, null=True)),
                ('contact', models.CharField(max_length=100)),
                ('service_call_date', models.DateField()),
                ('time', models.TimeField()),
                ('nature_of_fault', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment_details', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_resolved', models.DateField(blank=True, null=True)),
                ('customer_satisfied', models.BooleanField(default=False)),
                ('invoice_received_date', models.DateField(blank=True, null=True)),
                ('invoice_authorised_date', models.DateField(blank=True, null=True)),
                ('maintenance', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_services', to='customers.customer')),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engineers.engineer')),
                ('install_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.installlevel')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
            options={
                'db_table': 'services',
                'ordering': ['-created_at'],
            },
        ),
    ]
