# Generated by Django 5.0.6 on 2024-07-16 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_invoice_customers_i_custome_e86ce7_idx_and_more'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='invoice_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.invoice'),
        ),
        migrations.AlterField(
            model_name='po',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
