# Generated by Django 5.0.6 on 2025-01-02 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Engineer Company',
                'db_table': 'engineer_company',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('engineer_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('office_number', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('postcode_coverage', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_expiration', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('current_sla', models.CharField(blank=True, max_length=255, null=True)),
                ('performance_rating', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], max_length=2)),
                ('engineer_priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True)),
                ('is_telematics', models.BooleanField(default=False)),
                ('is_dashcam', models.BooleanField(default=False)),
                ('is_dvs', models.BooleanField(default=False)),
                ('is_dvr', models.BooleanField(default=False)),
                ('is_adr_tanker', models.BooleanField(default=False)),
                ('is_specialist_vehicles', models.BooleanField(default=False)),
                ('is_insurance_on_file', models.BooleanField(default=False)),
                ('is_current_sla', models.BooleanField(default=False)),
                ('is_other', models.BooleanField(default=False)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.installtype')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engineers.engineercompany')),
            ],
            options={
                'verbose_name_plural': 'Engineer',
                'db_table': 'engineer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EngineerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sp_comms_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('eng_invoice_received', models.DateField(blank=True, null=True)),
                ('eng_invoice_paid', models.DateField(blank=True, null=True)),
                ('invoice_notes', models.TextField(blank=True, null=True)),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engineers.engineer')),
            ],
            options={
                'verbose_name_plural': 'Engineer Invoice',
                'db_table': 'engineer_invoice',
                'managed': True,
            },
        ),
    ]
