# Generated by Django 5.0.6 on 2024-07-30 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_priority', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode_coverage', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('out_of_hours', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('office_number', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('insurance_expires', models.DateField(blank=True, null=True)),
                ('insurance_docs_received', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('current_sla', models.CharField(blank=True, max_length=255, null=True)),
                ('performance_rating', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], max_length=2)),
                ('confirm_by', models.CharField(blank=True, max_length=50, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.installtype')),
                ('engineer_priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engineers.engineerpriority')),
            ],
        ),
        migrations.CreateModel(
            name='EngineerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_comms_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('eng_invoice_received', models.DateField(blank=True, null=True)),
                ('eng_invoice_paid', models.DateField(blank=True, null=True)),
                ('invoice_notes', models.TextField(blank=True, null=True)),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engineers.engineer')),
            ],
        ),
    ]
