# Generated by Django 5.0.6 on 2025-01-18 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_is_engineer_company'),
        ('engineers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company'),
        ),
        migrations.DeleteModel(
            name='EngineerCompany',
        ),
    ]
