# Generated by Django 5.0.6 on 2024-09-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='engineer_priority',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('x', 'X')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='EngineerPriority',
        ),
    ]
