# Generated by Django 5.0.6 on 2024-07-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.AlterField(
            model_name='engineer',
            name='confirm_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='engineer_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
