# Generated by Django 5.0.6 on 2024-09-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0002_engineercompany_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineercompany',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engineercompany',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='engineerinvoice',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engineerinvoice',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='engineerpricing',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engineerpricing',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='engineerservice',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engineerservice',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
    ]
