# Generated by Django 5.0.6 on 2024-09-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0002_alter_engineer_engineer_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engineer',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='engineercompany',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='engineerinvoice',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='engineer',
            table='engineer',
        ),
        migrations.AlterModelTable(
            name='engineercompany',
            table='engineer_company',
        ),
        migrations.AlterModelTable(
            name='engineerinvoice',
            table='engineer_invoice',
        ),
    ]
