# Generated by Django 5.0.6 on 2024-09-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0003_engineercompany_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineercompany',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='engineerinvoice',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='engineerpricing',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='engineerservice',
            old_name='is_updated',
            new_name='is_active',
        ),
    ]
