# Generated by Django 5.0.6 on 2024-09-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0004_alter_engineer_options_alter_engineercompany_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engineer',
            options={'managed': True, 'verbose_name_plural': 'Engineer'},
        ),
        migrations.AlterModelOptions(
            name='engineercompany',
            options={'managed': True, 'verbose_name_plural': 'Engineer Company'},
        ),
        migrations.AlterModelOptions(
            name='engineerinvoice',
            options={'managed': True, 'verbose_name_plural': 'Engineer Invoice'},
        ),
    ]
