# Generated by Django 5.0.6 on 2024-09-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0004_rename_is_updated_engineercompany_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineerservice',
            name='engineer',
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='confirm_method',
        ),
        migrations.AddField(
            model_name='engineer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='engineer',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engineer',
            name='insurance_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engineer',
            name='is_adr_tanker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engineer',
            name='is_current_sla',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engineer',
            name='is_dashcam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engineer',
            name='is_dvr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engineer',
            name='is_dvs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engineer',
            name='is_insurance_on_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engineer',
            name='is_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engineer',
            name='is_specialist_vehicles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engineer',
            name='is_telematics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engineer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='engineer',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='EngineerPricing',
        ),
        migrations.DeleteModel(
            name='EngineerService',
        ),
    ]
