# Generated by Django 5.0.6 on 2024-09-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0005_alter_engineer_options_alter_engineercompany_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineer',
            old_name='confirm_by',
            new_name='confirm_method',
        ),
    ]
