# Generated by Django 5.0.6 on 2024-09-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0005_remove_engineerservice_engineer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
