# Generated by Django 5.0.6 on 2024-09-08 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0006_rename_confirm_by_engineer_confirm_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='insurance_docs_received',
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='insurance_expires',
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='out_of_hours',
        ),
        migrations.AlterField(
            model_name='engineer',
            name='engineer_priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='EngieerPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('de_re', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('de_installation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('upgrade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tracking_install', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('engineer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engineers.engineer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngineerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_car_kit_system', models.BooleanField(default=False)),
                ('is_ice_system', models.BooleanField(default=False)),
                ('is_alarm_system', models.BooleanField(default=False)),
                ('is_tracking_system', models.BooleanField(default=False)),
                ('engineer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engineers.engineer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
