# Generated by Django 5.0.6 on 2024-09-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0007_remove_engineer_insurance_docs_received_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EngieerPricing',
            new_name='EngineerPricing',
        ),
    ]
