# Generated by Django 5.0.6 on 2024-09-08 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0008_rename_engieerpricing_engineerpricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='engineer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='engineerpricing',
            name='engineer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engineers.engineer'),
        ),
        migrations.AlterField(
            model_name='engineerservice',
            name='engineer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engineers.engineer'),
        ),
    ]
