# Generated by Django 5.0.6 on 2025-01-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_route', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('city_link_account', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=255, null=True)),
                ('add2', models.CharField(blank=True, max_length=100, null=True)),
                ('add3', models.CharField(blank=True, max_length=100, null=True)),
                ('add4', models.CharField(blank=True, max_length=100, null=True)),
                ('post_code', models.CharField(blank=True, max_length=20, null=True)),
                ('service_level', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_instructions', models.TextField(blank=True, null=True)),
                ('pud', models.BooleanField(default=False)),
                ('returns', models.BooleanField(default=False)),
                ('sat_delivery', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('labels', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dispatch',
                'ordering': ['-created_at'],
            },
        ),
    ]
