# Generated by Django 5.0.6 on 2025-06-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclemodel',
            old_name='name',
            new_name='model_name',
        ),
    ]
