# Generated by Django 5.0.6 on 2024-07-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audittrail',
            name='actioned_by',
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='account',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='original_invoice',
        ),
        migrations.DeleteModel(
            name='VehicleModel',
        ),
        migrations.DeleteModel(
            name='VehicleType',
        ),
        migrations.DeleteModel(
            name='AuditTrail',
        ),
        migrations.DeleteModel(
            name='Bulletin',
        ),
        migrations.DeleteModel(
            name='Credit',
        ),
    ]
