# Generated by Django 5.0.6 on 2024-08-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_vehiclemake_remove_vehiclemodel_model_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='vehicle_make',
        ),
    ]
