# Generated by Django 5.0.6 on 2024-07-16 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stock_code'),
        ('utilities', '0002_remove_audittrail_actioned_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasteerror',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
