# Generated by Django 5.0.6 on 2024-09-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_carmanufacturer_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmanufacturer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carmanufacturer',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ordertype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordertype',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='phonemanufacturer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phonemanufacturer',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='speedup',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speedup',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiclemake',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclemake',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
    ]
