# Generated by Django 5.0.6 on 2024-09-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0003_carmanufacturer_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmanufacturer',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='ordertype',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='phonemanufacturer',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='phonemodel',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='speedup',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='vehiclemake',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='vehiclemodel',
            old_name='is_updated',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='vehicletype',
            old_name='is_updated',
            new_name='is_active',
        ),
    ]
