# Generated by Django 5.0.6 on 2024-08-27 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0003_remove_vehiclemodel_vehicle_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='vehicle_make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.vehiclemake'),
        ),
    ]
