# Generated by Django 5.0.6 on 2024-09-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installtype',
            options={'managed': True, 'verbose_name_plural': 'Installation Types'},
        ),
        migrations.AlterModelTable(
            name='installtype',
            table='install_type',
        ),
    ]
