from django.db import models


class Customer(models.Model):
    customer_ref_number = models.CharField(max_length=100)
    actinic_reference = models.CharField(max_length=100, blank=True, null=True)
    contact_name = models.CharField(max_length=100, blank=True, null=True)
    phone_numbers = models.CharField(max_length=100, blank=True, null=True)
    install_address = models.CharField(max_length=255, blank=True, null=True)
    delivery_address = models.CharField(max_length=255, blank=True, null=True)
    delivery_postcode = models.CharField(max_length=20, blank=True, null=True)
    postcode2 = models.CharField(max_length=20, blank=True, null=True)
    email_address = models.EmailField(blank=True, null=True)
    registration_number = models.CharField(max_length=20, blank=True, null=True)
    vehicle_make = models.CharField(max_length=50, blank=True, null=True)
    vehicle_model = models.CharField(max_length=50, blank=True, null=True)
    stereo_upgrade = models.BooleanField(default=False)
    set_nav = models.BooleanField(default=False)
    kit_installed = models.CharField(max_length=100, blank=True, null=True)  # use product name
    job_required = models.CharField(max_length=255, blank=True, null=True)  # use install type data
    strip_antenna = models.BooleanField(default=False)
    tax_disc_antenns = models.BooleanField(default=False)
    leather_pod = models.BooleanField(default=False)
    auto_lead = models.BooleanField(default=False)
    booking_notes = models.TextField(blank=True, null=True)
    requested_by = models.ForeignKey('User', on_delete=models.SET_NULL, blank=True, null=True)
    sp_comms_supplied_kit = models.BooleanField(default=False)
    date_of_install = models.DateField(blank=True, null=True)
    time_of_install = models.TimeField(blank=True, null=True)
    install_notes = models.TextField(blank=True, null=True)
    customer_notified = models.BooleanField(default=False)
    customer_notified_time = models.DateTimeField(blank=True, null=True)
    email_request_confirmed = models.BooleanField(default=False)
    request_time_stamp = models.DateTimeField(blank=True, null=True)
    courtesy_call = models.BooleanField(default=False)
    courtesy_notes = models.TextField(blank=True, null=True)
    service_call_rod = models.CharField(max_length=100, blank=True, null=True)
    service_call_reference = models.CharField(max_length=100, blank=True, null=True)
    invoice_received = models.DateTimeField(null=True, blank=True)
    invoice_paid = models.DateTimeField(null=True, blank=True)
    invoice_note = models.TextField(blank=True, null=True)
    service = models.ForeignKey('Service', on_delete=models.SET_NULL, blank=True, null=True)
    original_complaint_date_time = models.DateTimeField(blank=True, null=True)
    complaint_detail = models.TextField(blank=True, null=True)
    who_took_complaint = models.ForeignKey('User', on_delete=models.SET_NULL, blank=True, null=True)
    complaint_resolution = models.TextField(blank=True, null=True)
    resolution_date = models.DateField(blank=True, null=True)
    kit_supplied = models.CharField(default=False)  # supplier name
    po_number_kit = models.CharField(max_length=100, blank=True, null=True)  # purchase order(PO) number
    kit_order_date = models.DateField(blank=True, null=True)
    kit_delivered_to = models.CharField(max_length=255, blank=True, null=True)
    kit_delivery_date = models.DateField(blank=True, null=True)
    bracket_supplied = models.CharField(blank=True, null=True)  # supplier name
    po_number_bracket = models.CharField(max_length=100, blank=True, null=True)
    bracket_type = models.CharField(max_length=100, blank=True, null=True)  # comes from order description
    bracket_order_date = models.DateField(blank=True, null=True)
    bracket_delivered_to = models.CharField(max_length=255, blank=True, null=True)
    bracket_delivery_date = models.DateField(blank=True, null=True)
    auto_lead_order_date = models.DateField(blank=True, null=True)
    auto_lead_supplied = models.CharField(max_length=255, blank=True, null=True)
    kit_confirm_delivery = models.DateField(blank=True, null=True)
    delivery_notes = models.CharField(max_length=255, blank=True, null=True)
    courier_tracking_number = models.CharField(max_length=100, blank=True, null=True)
    invoice_address = models.CharField(max_length=255, blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    preferred_install_date = models.DateField(blank=True, null=True)
    multi_site_link = models.CharField(max_length=255, blank=True, null=True)
    has_multi_site_link = models.BooleanField(default=False)
    is_purchasing_complete = models.BooleanField(default=False)
    purchasing_complete_time = models.DateTimeField(blank=True, null=True)
    sold_by = models.ForeignKey('User', on_delete=models.SET_NULL, blank=True, null=True)
    customer_confirmed_by = models.ForeignKey('User', on_delete=models.SET_NULL, blank=True, null=True)
    customer_confirmed_time = models.DateTimeField(blank=True, null=True)
    acc_inv_raised_date = models.DateField(blank=True, null=True)
    acc_inv_paid = models.CharField(max_length=255, blank=True, null=True)
    is_on_hold = models.BooleanField(default=False)
    record_edited_at = models.DateTimeField(blank=True, null=True)
    service_reference_org = models.CharField(max_length=100, blank=True, null=True)
    call_back_reason = models.CharField(max_length=100, blank=True, null=True)
    stock_to_be_returned = models.CharField(max_length=100, blank=True, null=True)
    service_call_enabled = models.BooleanField(default=False)
    call_back_date = models.DateField(blank=True, null=True)
    post_code1 = models.CharField(max_length=20, blank=True, null=True)
    install_address_2 = models.CharField(max_length=255, blank=True, null=True)
    install_address_3 = models.CharField(max_length=255, blank=True, null=True)
    install_address_4 = models.CharField(max_length=255, blank=True, null=True)
    delivery_address_2 = models.CharField(max_length=255, blank=True, null=True)
    delivery_address_3 = models.CharField(max_length=255, blank=True, null=True)
    delivery_address_4 = models.CharField(max_length=255, blank=True, null=True)
    dispatched_date = models.DateField(blank=True, null=True)
    dispatched = models.BooleanField(default=False)
    bracket_po = models.CharField(max_length=100, blank=True, null=True)
    auto_lead_po = models.CharField(max_length=100, blank=True, null=True)
    is_web = models.BooleanField(default=False)
    instlev = models.CharField(max_length=100, blank=True, null=True)
    is_dispatch_printed = models.BooleanField(default=False)
    eng_inv_no = models.CharField(max_length=100, blank=True, null=True)
    is_hot = models.BooleanField(default=False)
    jcd = models.DateField(blank=True, null=True)
    sat = models.BooleanField(default=False)
    late = models.BooleanField(default=False)
    dispatch_route = models.CharField(max_length=100, blank=True, null=True)
    consignment = models.CharField(max_length=100, blank=True, null=True)
    dispute_eng_inv = models.BooleanField(default=False)
    dispute_eng_reason = models.CharField(max_length=100, blank=True, null=True)
    dispute_by = models.CharField(max_length=100, blank=True, null=True)
    back_order = models.BooleanField(default=False)
    existing_kit = models.BooleanField(default=False)
    package = models.CharField(max_length=100, blank=True, null=True)
    company = models.ForeignKey('Company', on_delete=models.SET_NULL, blank=True, null=True)
    account = models.ForeignKey('Account', on_delete=models.SET_NULL, blank=True, null=True)
    engineer = models.ForeignKey('Engineer', on_delete=models.SET_NULL, null=True, blank=True)
    vehicle_type = models.ForeignKey('VehicleType', on_delete=models.SET_NULL, blank=True, null=True)

    class Meta:
        verbose_name_plural = "Customers"
